import { execFileSync } from 'node:child_process';

/**
 * Apply the fixes on a branch and open a pull request for them.
 *
 * Never pushes to the branch under test. The output of this tool is a proposal a person
 * reads and merges; an accessibility tool that edits a protected branch on its own is
 * exactly the shape of automation that ends up disabled after the first surprise.
 */

const run = (cmd, args, opts = {}) =>
  execFileSync(cmd, args, { encoding: 'utf8', stdio: 'pipe', ...opts });

const version = process.env.A11YFIX_VERSION || 'latest';
const target = process.env.A11YFIX_PATH || '.';
const level = process.env.A11YFIX_LEVEL || 'AA';
const includeReview = String(process.env.A11YFIX_INCLUDE_REVIEW ?? 'false') === 'true';

const base = run('git', ['rev-parse', '--abbrev-ref', 'HEAD']).trim();
const branch = `a11yfix/${base.replace(/[^\w.-]+/g, '-')}`;

run('git', ['config', 'user.name', 'a11yfix[bot]']);
run('git', ['config', 'user.email', '41898282+github-actions[bot]@users.noreply.github.com']);
run('git', ['checkout', '-B', branch]);

const args = ['--yes', `a11yfix@${version}`, target, '--fix', '--level', level];
if (includeReview) args.push('--include-review');
try {
  run('npx', args, { shell: process.platform === 'win32' });
} catch (err) {
  // Exit 1 means findings remain, which is expected: not every finding has a patch.
  if (String(err.stderr ?? '').includes('could not')) {
    console.log(`::error::a11yfix failed: ${String(err.stderr).slice(0, 500)}`);
    process.exit(1);
  }
}

const dirty = run('git', ['status', '--porcelain']).trim();
if (dirty === '') {
  console.log('a11yfix: nothing to patch.');
  process.exit(0);
}

const changed = dirty.split('\n').length;
run('git', ['add', '-A']);
run('git', [
  'commit',
  '-m',
  `Fix accessibility violations in ${changed} file${changed === 1 ? '' : 's'}`,
  '-m',
  'Generated by a11yfix. Every change is a colour, an attribute or an element that had\n' +
    'exactly one correct value; nothing that required judgement was written. Findings that\n' +
    'need a person are listed in the run summary and are not touched here.',
]);

try {
  run('git', ['push', '--force-with-lease', 'origin', branch]);
} catch (err) {
  console.log(`::error::could not push ${branch}: ${String(err.stderr ?? err.message).slice(0, 300)}`);
  console.log('::error::"pr" mode needs a token with contents: write and pull-requests: write.');
  process.exit(1);
}

const body = [
  'Automated accessibility fixes.',
  '',
  `Applied to ${changed} file${changed === 1 ? '' : 's'} by [a11yfix](https://github.com/iam-artificis/a11yfix)` +
    (includeReview ? ', including fixes marked "review".' : ', restricted to fixes that are correct independent of context.'),
  '',
  'What is **not** in this pull request: anything that needs a human decision. No alternative',
  'text was invented, no link text was written, no language tag was guessed. Those are reported',
  'with a marker and left alone, because a plausible-sounding wrong description is worse than a',
  'missing one — it lies to a screen-reader user and makes every checker report the page as fixed.',
  '',
  'Merging this does not make the project WCAG conformant. It clears the machine-checkable part',
  'so a human review can start from a smaller pile.',
].join('\n');

try {
  const url = run('gh', ['pr', 'create', '--base', base, '--head', branch, '--title', 'Fix accessibility violations', '--body', body]);
  console.log(`a11yfix: opened ${url.trim()}`);
} catch (err) {
  const message = String(err.stderr ?? err.message);
  if (/already exists/i.test(message)) {
    console.log('a11yfix: the pull request already exists and has been updated.');
  } else {
    console.log(`::error::could not open a pull request: ${message.slice(0, 300)}`);
    process.exit(1);
  }
}
